name: replace-in-files
files:
  - 'src/**/*.md'
  - 'src/**/*.mdx'
  - '.*'
  - '*'
  - '!node_modules'
  - '!rif.config.yaml'
replacements:
  - from: /docs-starlight-description/g
    to: Antd components wrapped.
  - from: /docs-starlight/g
    to: antd-components-example
